### ISSUE TITLE
Feature request: Join job actions based on valheim-vanity variables

### ISSUE THREAD

**Issue by psymin** [JereKuusela/valheim-cron_job#16]
I would like to be able to encourage players to avoid bringing items from other servers to my local server.

One method might be to enhance Join job to take action based on equipped items.

Example:

```
join:
  - command: kick <id>
    equipped: HelmetBronze
```

**Comment by psymin** [comment]
It sounds like something similar might be possible using
https://github.com/JereKuusela/valheim-expand_world_prefabs

```
- prefab: Player
  type: state
  command: say <pid>
  filters:
  - hash, HelmetItem, HelmetBronze, HelmetIron
```
