### ISSUE TITLE
Feature request: Zone jobs taking action on players

### ISSUE THREAD

**Issue by psymin** [JereKuusela/valheim-cron_job#17]
I would like to be able to encourage players to avoid going into certain areas.

One method might be to expand Zone jobs to be able to take action on players in the zone.

Example:

```
zone:
  - command: kick <id>
    schedule: "* * * * *"
    biomes: BlackForest
```

**Comment by psymin** [comment]
Another option might be to have Player jobs.

Example:

```
player:
 - command: kick <id>
   biomes: BlackForest
   schedule: "* * * * *"
```
