### ISSUE TITLE
DateTime error using basic example

### ISSUE THREAD

**Issue by viperp12** [JereKuusela/valheim-cron_job#2]
Looking into it as well. 

cron.yaml values:

```
jobs: []
zone:
  - command: locations_reset Crypt2 zone=$$i,$$j start
    inactive: 60
  - command: vegetation_reset rock4_copper zone=$$i,$$j start
    schedule: "0 11 * * *"
```

```
ArgumentException: The supplied DateTime must have the Kind property set to Utc
Parameter name: fromUtc
  at Cronos.CronExpression.ThrowWrongDateTimeKindException (System.String paramName) [0x00000] in <110e79fd2e624acc963031637c1fb33d>:0
  at Cronos.CronExpression.GetNextOccurrence (System.DateTime fromUtc, System.Boolean inclusive) [0x0000a] in <110e79fd2e624acc963031637c1fb33d>:0
  at CronJob.CronManager.Parse (System.String value, System.Nullable`1[T] next) [0x0001f] in <110e79fd2e624acc963031637c1fb33d>:0
  at CronJob.CronManager.Execute (Vector2i zone, System.Nullable`1[T] previous) [0x00032] in <110e79fd2e624acc963031637c1fb33d>:0
  at CronJob.TrackManager.Poke (Vector2i zone) [0x0002b] in <110e79fd2e624acc963031637c1fb33d>:0
  at CronJob.TrackManager.Track () [0x00071] in <110e79fd2e624acc963031637c1fb33d>:0
  at CronJob.CronJob.LateUpdate () [0x00047] in <110e79fd2e624acc963031637c1fb33d>:0
```
